#!/bin/sh

set -e

DIR="$(pwd)"

if [[ -e tmp || -e log || -e out ]] ; then
  echo "Directories \"tmp\", \"log\" and \"out\" must be deleted."
  exit 1
fi

mkdir -p "$DIR/log"
mkdir -p "$DIR/tmp/scrape"
cd "$DIR/tmp/scrape"
python2 /usr/lib/hinance/scrape.py -addv --logging-file "$DIR/log/scrape.log"

mkdir -p "$DIR/tmp/src/hs"
cp -t "$DIR/tmp/src/hs" "$HOME/.hinance/*.hs" /usr/lib/hinance/hs/*
cp -rt "$DIR/tmp/src" /usr/lib/hinance/{*.clj,cljs}
cp "$HOME/.hinance/*.cljs" "$DIR/tmp/src/cljs/hinance"

echo -e "module Hinance.Bank.Data where\nimport Hinance.Bank.Type\n\
import Hinance.Currency\nbanksraw = []" >"$DIR/tmp/src/hs/bank_data.hs"
echo -e "module Hinance.Shop.Data where\nimport Hinance.Shop.Type\n\
import Hinance.Currency\nshopsraw = []" >"$DIR/tmp/src/hs/shop_data.hs"

set +e
cat {"$HOME/.hinance","$DIR/tmp/scrape"}/banks*.hs.part \
  >> "$DIR/tmp/src/hs/bank_data.hs"
cat {"$HOME/.hinance","$DIR/tmp/scrape"}/shops*.hs.part \
  >> "$DIR/tmp/src/hs/shop_data.hs"
set -e

ghc -O -XFlexibleInstances -o "$DIR/tmp/hinance-hs" "$DIR/tmp/src/hs/*.hs"

echo 'Generating report source.'
echo -e "(ns hinance.data (:require hinance.type))\n\n\
(def timestamp \"$(date +'%Y-%m-%d %H:%M %Z')\")" \
  >"$DIR/tmp/src/cljs/hinance/data.cljs"
"$DIR/tmp/hinance-hs" >>"$DIR/tmp/src/cljs/hinance/data.cljs"

cd "$DIR/tmp/src"
lein cljsbuild once

mkdir -p "$DIR/out"
cp -t "$DIR/out" "$DIR/tmp/src/hinance.js" /var/lib/hinance/hinance.html
