#!/bin/bash

set -e

for NAME in user_{data,tag}.hs backends ; do
  if [[ ! -e in/$NAME ]] ; then
    echo "File \"in/$NAME\" is required to continue."
    exit 1
  fi
done

if [ -e out/lock.pid ] ; then
  if kill -0 $(cat out/lock.pid) &>/dev/null ; then
    echo "hinance is already running in the current directory."
    exit 1
  fi
fi

mkdir -p cmd out/{log,arc,www}
echo $$ > out/lock.pid

if [ ! -e in/config.sh ] ; then cp /usr/lib/hinance/config.sh in ; fi
. in/config.sh

echo "Serving."
DIR="$(pwd)"
while true ; do
  TIMEBEGIN=$(date +"%s")
  DATE=$(date +"%Y_%m_%d_%H_%M")
  echo "Cycle started for $DATE" >> "$DIR"/out/log/hinance.log

  ARCDIR="$DIR"/out/arc/$DATE
  rm -rf $ARCDIR
  mkdir -p $ARCDIR
  cp "$DIR/in/*" $ARCDIR
  chmod 600 "$ARCDIR"/backends
  export WEBOOB_BACKENDS="$ARCDIR"/backends
  
  cd $ARCDIR
  if /usr/lib/hinance/hinance-once &>> "$DIR"/out/log/hinance.log ; then
    rm -rf "$DIR"/out/www
    mv out/www "$DIR"/out
  fi
  rm -rf tmp

  echo "Cycle finished for $DATE" >> "$DIR"/out/log/hinance.log

  while (( $(date +"%s") < TIMEBEGIN + RESTART_PERIOD )) ; do
    if [ -e "$DIR"/cmd/restart ] ; then
      rm -f "$DIR"/cmd/restart
      break
    fi
    sleep 1
  done
done
