#!/bin/sh

set -e

DIR="$(pwd)"

for NAME in tmp log out ; do
  if [[ -e $NAME ]] ; then
    echo "Directory \"$NAME\" must be deleted to continue."
    exit 1
  fi
done

for NAME in user_{data,tag}.hs user.cljs ; do
  if [[ ! -e $NAME ]] ; then
    echo "File \"$NAME\" is required to continue."
    exit 1
  fi
done

mkdir -p "$DIR/"{log,out}
cd "$DIR/out"
python2 /usr/lib/hinance/scrape.py -ddv --logging-file "$DIR/log/scrape.log"

mkdir -p "$DIR/tmp/hs"
cp -t "$DIR/tmp/hs" "$DIR"/*.hs /usr/lib/hinance/hs/*
cp -rt "$DIR/tmp" /usr/lib/hinance/{*.clj,cljs}
cp "$DIR"/*.cljs "$DIR"/tmp/cljs/hinance

echo -e "module Hinance.Bank.Data where\nimport Hinance.Bank.Type\n\
import Hinance.Currency\nbanksraw = []" >"$DIR/tmp/hs/bank_data.hs"
echo -e "module Hinance.Shop.Data where\nimport Hinance.Shop.Type\n\
import Hinance.Currency\nshopsraw = []" >"$DIR/tmp/hs/shop_data.hs"

set +e
cat "$DIR"/{,out/}banks*.hs.part >> "$DIR/tmp/hs/bank_data.hs"
cat "$DIR"/{,out/}shops*.hs.part >> "$DIR/tmp/hs/shop_data.hs"
set -e

ghc -O -XFlexibleInstances -o "$DIR/tmp/hinance-hs" "$DIR"/tmp/hs/*.hs

echo 'Generating report web pages.'
"$DIR/tmp/hinance-hs" &
PID=$!

while kill -0 $PID 2>/dev/null ; do
  du -hd0 "$DIR/out"
  sleep 10
done

wait $PID

cd "$DIR/tmp"
lein cljsbuild once

cp -t "$DIR/out" "$DIR/tmp/hinance.js" /usr/lib/hinance/hinance.html
